
# Supabase Project Configuration

[auth]
site_url = "https://les-stagiere.vercel.app"
additional_redirect_urls = [
  "https://les-stagiere.vercel.app", 
  "https://les-stagiere.vercel.app/email-confirmation",
  "https://les-stagiere.vercel.app/email-confirmation?type=signup",
  "https://les-stagiere.vercel.app/email-confirmation?type=recovery",
  "https://les-stagiere.vercel.app/connexion",
  "https://les-stagiere.vercel.app/stagiaires/*",
  "https://les-stagiere.vercel.app/entreprises/*",
  "https://les-stagiere.vercel.app/*",
  "https://les-stagiere.vercel.app/connexion?error=confirmation_failed",
  "https://les-stagiere.vercel.app/entreprises",
  "https://les-stagiere.vercel.app/stagiaires",
  "https://les-stagiere.vercel.app/",
  "https://les-stagiere.vercel.app/index.html",
  "http://localhost:5173",
  "http://localhost:5173/email-confirmation",
  "http://localhost:5173/email-confirmation?type=signup",
  "http://localhost:5173/email-confirmation?type=recovery",
  "http://localhost:5173/connexion",
  "http://localhost:5173/stagiaires/*",
  "http://localhost:5173/entreprises/*",
  "http://localhost:5173/connexion?error=confirmation_failed",
  "http://localhost:5173/*",
  "http://localhost:5173/entreprises",
  "http://localhost:5173/stagiaires",
  "http://localhost:5173/",
  "http://localhost:5173/index.html",
  "http://localhost:3000",
  "http://localhost:3000/email-confirmation",
  "http://localhost:3000/connexion",
  "http://localhost:3000/stagiaires/*",
  "http://localhost:3000/entreprises/*",
  "http://localhost:3000/*",
  "http://localhost:3000/entreprises",
  "http://localhost:3000/stagiaires",
  "http://localhost:3000/",
  "http://localhost:3000/index.html"
]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[storage]
file_size_limit = "50MiB"

[api]
enabled_apis = ["rest", "graphql", "realtime"]
