
# Supabase Project Configuration

[auth]
site_url = "https://les-stagiere.vercel.app"
additional_redirect_urls = ["https://les-stagiere.vercel.app", "https://les-stagiere.vercel.app/email-confirmation"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[storage]
file_size_limit = "50MiB"

[api]
enabled_apis = ["rest", "graphql", "realtime"]
